groupName: acme.yourdomain.tld

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

image:
  registry: ghcr.io
  repository: sshine/cert-manager-webhook-hetzner
  tag: ""
  pullPolicy: IfNotPresent

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 443

secretName:
  - hetzner-secret

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]

podSecurityContext:
  runAsGroup: 1000
  runAsUser: 1000
  runAsNonRoot: true

priorityClassName: ""
