version: "2"
run:
  modules-download-mode: mod
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    depguard:
      rules:
        main:
          files:
            - '!**/*_a _file.go'
          allow:
            - $gostd
            - k8s.io/apiextensions-apiserver
            - k8s.io/apimachinery
            - k8s.io/client-go/kubernetes
            - k8s.io/client-go/rest
            - k8s.io/klog/v2
            - github.com/cert-manager/cert-manager
            - github.com/vadimkim/cert-manager-webhook-hetzner/internal
          deny:
            - pkg: github.com/sirupsen/logrus
              desc: not allowed
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package
    gocritic:
      disabled-checks:
        - whyNoLint
        - wrapperFunc
      enabled-tags:
        - performance
        - style
        - experimental
    gosec:
      excludes:
        - G404
    misspell:
      locale: US
    revive:
      rules:
        - name: var-naming
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/golangci/golangci-lint
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
